spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=password

server.port=9002
management.server.port=9002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.application.name=auth-service
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0

JWT_SECRET=G42GGZhPVLt/SSRNriBt9iiCZfD5B7DvNGR4Oq/YZocGX74xgHLvJqIpq+3iAhud4aKlcnujU2LYkBt6aeTfHQ=
JWT_EXPIRATION=8640000
