export const FETCH_REGISTRY = "FETCH_REGISTRY";
export const FETCH_REGISTRY_SUCCESS = "FETCH_REGISTRY_SUCCESS";
export const FETCH_REGISTRY_ERROR = "FETCH_REGISTRY_ERROR";

export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";

export const FETCH_EXISTS = "FETCH_EXISTS";
export const FETCH_EXISTS_SUCCESS = "FETCH_EXISTS_SUCCESS";
export const FETCH_EXISTS_ERROR = "FETCH_EXISTS_ERROR";